name: Custom Actions
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - name: Change Node.js Version
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.16.0
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: Pavel Keyzik
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
