name: CI/CD Workflow

on:
  pull_request:
  push:
    branches:
      - "main"
      - "next"
      - "version/**"

jobs:
  # Check jobs
  file-structure:
    if: false
    name: Files structure
    runs-on: ubuntu-22.04
    steps:
      - name: Get project files
        uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/before-job
      - name: Verify files structure
        run: echo "Verify files structure"
  lint:
    if: false
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Get project files
        uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/before-job
      - name: Check for linting issues
        run: echo "Check for linting issues"
  pull-request:
    name: Pull Request
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Get project files
        uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/before-job
      - name: Check for Pull Request configuration
        run: npx auto pr-check --url ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} --pr ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  test:
    if: false
    name: Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Get project files
        uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/before-job
      - name: Run tests
        run: echo "Run tests"
      - name: Upload Code Coverage
        run: echo "Upload Code Coverage"
  typescript:
    if: false
    name: TypeScript
    runs-on: ubuntu-22.04
    steps:
      - name: Get project files
        uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/before-job
      - name: Check for TypeScript issues
        run: echo "Check for TypeScript issues"
  code-climate:
    name: Code Climate Coverage
    runs-on: ubuntu-22.04
    steps:
      - name: Get project files
        uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/before-job
      - run: npm install
      - run: npm run coverage
      - name: Upload Coverage
        run: |
          wget https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -O cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          ./cc-test-reporter format-coverage coverage/clover.xml -t clover
          ./cc-test-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ae779a41f8ada870fed40c9b8718f00fe40369c4381d70304979366edba78e51

  # Build jobs
  package-build:
    name: Build package
    runs-on: ubuntu-22.04
    needs:
      - file-structure
      - lint
      - test
      - typescript
    steps:
      - name: Get project files
        uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/before-job
      - name: Build
        run: |
          echo "Build"
          mkdir dist
          cd dist
          echo "Something" > index.js
          ls -a
          cat index.js
          cd ../
      # - name: Install Chromium
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y chromium
      - name: Install Dependencies
        run: npm install
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dist
          path: dist
          retention-days: 1
  storybook-build:
    name: Build storybook
    runs-on: ubuntu-22.04
    needs:
      - file-structure
      - lint
      - test
      - typescript
    steps:
      - name: Get project files
        uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/before-job
      - name: Build
        run: |
          mkdir storybook-static
          cd storybook-static
          echo "<h1>Storybook</h1>" > index.html
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: storybook-static
          path: storybook-static
          retention-days: 1
  storybook-publish:
    name: Publish Storybook
    runs-on: ubuntu-22.04
    needs:
      - storybook-build
    steps:
      - name: Get project files
        uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/before-job
      - name: Publish Storybook
        run: echo "Publish Storybook"
