name: CI

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Change Node.js Version
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.18.1
      - name: Cache node_modules
        uses: actions/cache@v3.3.1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

          # if GitHub didn't find cash from `key` then we could try to find
          # old caches that start with anything provided in `restore-key`
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci
      - name: Check code format
        run: npm run format:check
      - name: Run unit tests
        run: npm run test
      - name: Generate Coverage Report
        run: npm run coverage
        env:
          CI: true
      - name: Build project
        if: github.event_name == 'push' # Only when we push to develop branch
        run: npm run build
      - name: Deploy to Staging
        if: github.event_name == 'push' # Only when we push to develop branch
        run: npx surge --project ./dist --domain rainy-stream.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
