name: Docker Container

on: push

jobs:
  node-docker:
    if: ${{ false }} # Just disable this job
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.16 # Image from Docker Hub
      # volumes:
      # ports:
      # env: 
      # ...
    steps:
      - name: Log version
        run: |
          node -v
          cat /etc/os-release
