name: Matrix

on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [6, 8, 10] # This will run job 3 times for each version
      fail-fast: true # if one of these jobs fails, then we don't run others

      # By default, GitHub will maximize the number of jobs
      # run in parallel depending on the available runners
      # max-parallel: 2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - uses: 'actions/setup-node@v3.6.0'
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log node version After Action
        run: node -v