name: Matrix

on: push

jobs:
  node-version:
    if: ${{ false }} # Just disable this job
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node_version: [6, 8, 10] # This will run job 3 times for each version
        include: # with include we could add additional variables for specific cases
          - os: ubuntu-latest
            node_version: 8
            is_ubuntu_8: "true"
        exclude:
          - os: macos-latest
            node_version: 8
          - os: ubuntu-latest
            node_version: 6
      fail-fast: true # if one of these jobs fails, then we don't run others

      # By default, GitHub will maximize the number of jobs
      # run in parallel depending on the available runners
      # max-parallel: 2
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: Log node version
        run: |
          node -v
          echo "IS_UBUNTU_8: ${IS_UBUNTU_8}"
      - uses: 'actions/setup-node@v3.6.0'
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version After Action
        run: node -v