name: Shell Commands # Workflow Name

on: [push] # Events

jobs:
  run-shell-command: # Job Name
    runs-on: ubuntu-latest
    steps:
      - name: log a string # Step Name
        run: echo "Hey there 👋" # Script
      - name: multiline script # Step Name
        run: | # Multiple scripts
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python # Change shell
  run-windows-commands:
    runs-on: windows-latest
    needs: [run-shell-command] # Runs `run-shell-command` first and after success runs current job 
    steps:
      - name: get directory from powershell
        run: Get-Location
      - name: get directory from bash
        run: pwd
        shell: bash