name: Workflow With Environment Test

on:
  push:
  workflow_dispatch:
    inputs:
      withCanaryDeploy:
        description: "Run with deploy"
        required: true
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tests"
      - run: echo "${{ inputs.tags }}"
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{ inputs.withCanaryDeploy }}" == "true" ]]
          then
            echo "Releasy canary"
          elif [[ ${{ github.event_name != 'pull_request' }} ]]
          then
            echo "Regular release"
          else
            echo "Skip release"
          fi
