name: Workflow With Environment Test

on:
  push:
  workflow_dispatch:
    inputs:
      withCanaryDeploy:
        description: "Run with deploy"
        required: true
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tests"
      - run: echo "${{ inputs.tags }}"
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' || github.event_name == 'push'
    steps:
      - run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ "${{ inputs.withCanaryDeploy }}" == "true" ]]; then
              echo "Release Canary Version"
            else
              echo "Skip Version"
            fi
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo "Release"
          else
            echo "Skip Release"
          fi
